apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: edot-observability
servers: 1
agents: 2
image: rancher/k3s:v1.31.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
