apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:0.49.0
          args: ["run", "/scripts/scenario.js"]
          env:
            - name: TARGET_URL
              value: "http://frontend:8080/"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: k6-scripts
